Repository digitalfabrik/entitlementcard, pull requests merged in 2025-05, with the labels that each got.

#2041 1689: Add linting to frontend build config
  .circleci/config.yml
  .circleci/src/jobs/check_frontend.yml
  .circleci/src/workflows/commit.yml
  .idea/runConfigurations/Format_Code.xml
  .prettierrc
  administration/eslint.config.mjs
  administration/package.json
  eslint.config-base.mjs
  frontend/build-configs/.prettierignore
  frontend/build-configs/.prettierrc
  frontend/build-configs/bayern/index.ts
  frontend/build-configs/constants/index.ts
  frontend/build-configs/eslint.config.mjs
  frontend/build-configs/index.ts
  frontend/build-configs/koblenz/index.ts
  frontend/build-configs/nuernberg/index.ts
  frontend/build-configs/package.json
  frontend/build-configs/tsconfig.json
  frontend/build-configs/types.ts
  package-lock.json
  package.json
Labels: not-testable

#2104 2100: Update backend dependencies
  .circleci/config.yml
  .circleci/src/jobs/build_backend.yml
  .circleci/src/jobs/check_backend.yml
  .idea/runConfigurations/Test_backend.xml
  backend/build.gradle.kts
  backend/gradle.properties
  backend/gradle/libs.versions.toml
  backend/gradle/wrapper/gradle-wrapper.jar
  backend/gradle/wrapper/gradle-wrapper.properties
  backend/gradlew
  backend/gradlew.bat
  backend/settings.gradle.kts
  backend/src/main/kotlin/app/ehrenamtskarte/backend/EntryPoint.kt
  backend/src/main/kotlin/app/ehrenamtskarte/backend/application/database/Schema.kt
  backend/src/main/kotlin/app/ehrenamtskarte/backend/application/database/repos/ApplicationRepository.kt
  backend/src/main/kotlin/app/ehrenamtskarte/backend/application/webservice/EakApplicationMutationService.kt
  backend/src/main/kotlin/app/ehrenamtskarte/backend/application/webservice/EakApplicationQueryService.kt
  backend/src/main/kotlin/app/ehrenamtskarte/backend/application/webservice/dataloader/ApplicationDataLoader.kt
  backend/src/main/kotlin/app/ehrenamtskarte/backend/auth/database/repos/AdministratorsRepository.kt
  backend/src/main/kotlin/app/ehrenamtskarte/backend/auth/webservice/schema/ApiTokenService.kt
  backend/src/main/kotlin/app/ehrenamtskarte/backend/auth/webservice/schema/ChangePasswordMutationService.kt
  backend/src/main/kotlin/app/ehrenamtskarte/backend/auth/webservice/schema/ManageUsersMutationService.kt
  backend/src/main/kotlin/app/ehrenamtskarte/backend/auth/webservice/schema/NotificationSettingsMutationService.kt
  backend/src/main/kotlin/app/ehrenamtskarte/backend/auth/webservice/schema/NotificationSettingsQueryService.kt
  backend/src/main/kotlin/app/ehrenamtskarte/backend/auth/webservice/schema/ResetPasswordMutationService.kt
  backend/src/main/kotlin/app/ehrenamtskarte/backend/auth/webservice/schema/SignInMutationService.kt
  backend/src/main/kotlin/app/ehrenamtskarte/backend/auth/webservice/schema/ViewAdministratorsQueryService.kt
  backend/src/main/kotlin/app/ehrenamtskarte/backend/auth/webservice/schema/ViewPepperQueryService.kt
  backend/src/main/kotlin/app/ehrenamtskarte/backend/auth/webservice/schema/types/Administrator.kt
  backend/src/main/kotlin/app/ehrenamtskarte/backend/cards/database/Schema.kt
  backend/src/main/kotlin/app/ehrenamtskarte/backend/cards/database/repos/CardRepository.kt
  backend/src/main/kotlin/app/ehrenamtskarte/backend/cards/webservice/schema/CardMutationService.kt
  backend/src/main/kotlin/app/ehrenamtskarte/backend/cards/webservice/schema/CardQueryService.kt
  backend/src/main/kotlin/app/ehrenamtskarte/backend/cards/webservice/schema/CardStatisticsQueryService.kt
  backend/src/main/kotlin/app/ehrenamtskarte/backend/common/webservice/GraphQLContext.kt
  backend/src/main/kotlin/app/ehrenamtskarte/backend/common/webservice/GraphQLHandler.kt
  backend/src/main/kotlin/app/ehrenamtskarte/backend/freinet/webservice/FreinetAgencyMutationService.kt
  backend/src/main/kotlin/app/ehrenamtskarte/backend/freinet/webservice/FreinetAgencyQueryService.kt
  backend/src/main/kotlin/app/ehrenamtskarte/backend/migration/database/Schema.kt
  backend/src/main/kotlin/app/ehrenamtskarte/backend/regions/database/repos/RegionsRepository.kt
  backend/src/main/kotlin/app/ehrenamtskarte/backend/regions/webservice/dataloader/RegionDataLoader.kt
  backend/src/main/kotlin/app/ehrenamtskarte/backend/regions/webservice/schema/RegionsMutationService.kt
  backend/src/main/kotlin/app/ehrenamtskarte/backend/regions/webservice/schema/RegionsQueryService.kt
  backend/src/main/kotlin/app/ehrenamtskarte/backend/stores/database/GeometryColumnType.kt
  backend/src/main/kotlin/app/ehrenamtskarte/backend/stores/database/PointColumnType.kt
  backend/src/main/kotlin/app/ehrenamtskarte/backend/stores/database/Schema.kt
  backend/src/main/kotlin/app/ehrenamtskarte/backend/stores/database/repos/AcceptingStoresRepository.kt
  backend/src/main/kotlin/app/ehrenamtskarte/backend/stores/database/repos/PhysicalStoresRepository.kt
  backend/src/main/kotlin/app/ehrenamtskarte/backend/stores/importer/common/steps/Store.kt
  backend/src/main/kotlin/app/ehrenamtskarte/backend/stores/webservice/AcceptingStoresMutationService.kt
  backend/src/main/kotlin/app/ehrenamtskarte/backend/stores/webservice/schema/AcceptingStoreQueryService.kt
  backend/src/main/kotlin/app/ehrenamtskarte/backend/userdata/database/Schema.kt
  backend/src/main/kotlin/app/ehrenamtskarte/backend/userdata/webservice/UserImportHandler.kt
  backend/src/test/kotlin/app/ehrenamtskarte/backend/GraphqlApiTest.kt
  backend/src/test/kotlin/app/ehrenamtskarte/backend/application/webservice/Verein360ApplicationTest.kt
  backend/src/test/kotlin/app/ehrenamtskarte/backend/auth/webservice/ApiTokenServiceTest.kt
  backend/src/test/kotlin/app/ehrenamtskarte/backend/freinet/webservice/FreinetAgencyMutationServiceTest.kt
  backend/src/test/kotlin/app/ehrenamtskarte/backend/helper/ExampleCards.kt
  specs/backend-api.graphql
Labels: not-testable

#2155 2153: Fix latest
  package-lock.json
  package.json
Labels: not-testable

#2013 1972: Playwright e2e tests
  .idea/git_toolbox_blame.xml
  administration/.gitignore
  administration/.prettierignore
  administration/e2e-tests/bayern/check_applications.spec.ts
  administration/e2e-tests/bayern/create_applications.spec.ts
  administration/e2e-tests/bayern/delete_applications.spec.ts
  administration/eslint.config.mjs
  administration/package.json
  administration/playwright.config.ts
  administration/run-backend.sh
  docs/development-setup.md
  package-lock.json
Labels: not-testable

#2106 Add troubleshooting info on eak stores import failure
  docs/troubleshooting.md
Labels: not-testable

#2093 Add setup documentation
  backend/build.gradle.kts
  docs/development-setup.md
Labels: not-testable

#2162 Docs backend first steps
  README.md
  docs/working-with-graphql-api.md
Labels: not-testable

#2191 2190: Fix KOBLENZ_PEPPER in gradle config
  backend/build.gradle.kts
Labels: not-testable

#2194 Fix card activation
  backend/src/main/kotlin/app/ehrenamtskarte/backend/cards/webservice/schema/CardMutationService.kt
Labels: prio: high

#2202 Group dependabot updates and reduce frequency
  .github/dependabot.yaml
Labels: not-testable

#2196 1981.1: Refactor application overview in administration
  administration/package.json
  administration/src/App.tsx
  administration/src/bp-modules/applications/ApplicationCard.tsx
  administration/src/bp-modules/applications/ApplicationStatusBar.tsx
  administration/src/bp-modules/applications/ApplicationsController.tsx
  administration/src/bp-modules/applications/ApplicationsOverview.tsx
  administration/src/bp-modules/applications/NoteDialogController.tsx
  administration/src/bp-modules/applications/PreVerifiedQuickIndicator.tsx
  administration/src/bp-modules/applications/VerificationsQuickIndicator.tsx
  administration/src/bp-modules/components/CustomDatePicker.tsx
  administration/src/bp-modules/statistics/components/StatisticsFilterBar.test.tsx
  administration/src/bp-modules/statistics/components/StatisticsFilterBar.tsx
  administration/src/i18n.ts
  administration/src/mui-modules/NonIdealState.tsx
  administration/src/mui-modules/application/BasicDialog.tsx
  administration/src/mui-modules/theme.ts
  administration/src/project-configs/getProjectConfig.ts
  administration/src/types/mui-theme.d.ts
  administration/src/util/translations/de.json
  backend/src/dev/sql/applications.sql
  docs/development-setup.md
  frontend/build-configs/package.json
  package-lock.json
  package.json
Labels: javascript, web
