Repository digitalfabrik/entitlementcard, pull requests merged in 2025-06, with the labels that each got.

#2208 dependabot: Group updates patch single minor
  .github/dependabot.yaml
Labels: not-testable

#2193 1933: Fix null check on null value
  frontend/lib/map/location_button.dart
Labels: not-testable

#2241 Fix babel config
  administration/config/babel-dependencies.config.ts
Labels: not-testable

#2214 Post install restart backend after migration
  scripts/pack_deb.sh
Labels: not-testable

#2269 2267: Use '/' as public URL instead of localhost
  administration/config/getPaths.ts
Labels: not-testable

#2156 2268: Optimize backend tests performance
  backend/src/test/kotlin/app/ehrenamtskarte/backend/GraphqlApiTest.kt
  backend/src/test/kotlin/app/ehrenamtskarte/backend/IntegrationTest.kt
  backend/src/test/kotlin/app/ehrenamtskarte/backend/helper/TestAdministrators.kt
  backend/src/test/kotlin/app/ehrenamtskarte/backend/helper/TestFreinetAgencies.kt
  backend/src/test/kotlin/app/ehrenamtskarte/backend/userdata/UserImportTest.kt
Labels: not-testable

#2264 2260: Use sentry only for gradle production builds
  .circleci/config.yml
  .circleci/src/jobs/build_backend.yml
  backend/build.gradle.kts
Labels: not-testable, backend

#2246 2243: Unit tests card extensions
  administration/jest.setup.ts
  administration/src/bp-modules/applications/__tests__/PreVerifiedQuickIndicator.test.tsx
  administration/src/cards/__tests__/Card.test.ts
  administration/src/cards/extensions/BavariaCardTypeExtension.test.ts
  administration/src/cards/extensions/BirthdayExtension.tsx
  administration/src/cards/extensions/StartDayExtension.tsx
  administration/src/cards/extensions/__tests__/AddressFieldExtensions.test.ts
  administration/src/cards/extensions/__tests__/BavariaCardTypeExtension.test.tsx
  administration/src/cards/extensions/__tests__/BirthdayExtension.test.tsx
  administration/src/cards/extensions/__tests__/EMailNotificationExtension.test.ts
  administration/src/cards/extensions/__tests__/KoblenzReferenceNumberExtension.test.tsx
  administration/src/cards/extensions/__tests__/NuernbergPassIdExtension.test.tsx
  administration/src/cards/extensions/__tests__/RegionExtension.test.ts
  administration/src/cards/extensions/__tests__/StartDayExtension.test.tsx
  administration/src/cards/extensions/components/__tests__/CardTextField.test.tsx
  administration/src/mui-modules/base/FormAlert.tsx
  administration/src/util/translations/de.json
Labels: not-testable

#2249 1981.2: Approve application for Ehrenamtskarte Bayern
  .circleci/config.yml
  .circleci/src/jobs/check_administration.yml
  administration/@types/normalize-strings.d.ts
  administration/e2e-tests/bayern/check_applications.spec.ts
  administration/graphql-codegen.yml
  administration/package.json
  administration/src/AppApolloProvider.tsx
  administration/src/bp-modules/applications/ApplicationCard.tsx
  administration/src/bp-modules/applications/ApplicationStatusBar.tsx
  administration/src/bp-modules/applications/ApplicationStatusBarHelpButton.tsx
  administration/src/bp-modules/applications/ApplicationStatusBarItem.tsx
  administration/src/bp-modules/applications/ApplicationsOverview.tsx
  administration/src/bp-modules/applications/NoteDialogController.tsx
  administration/src/bp-modules/applications/PreVerifiedQuickIndicator.tsx
  administration/src/bp-modules/applications/VerificationsIndicator.tsx
  administration/src/bp-modules/applications/VerificationsQuickIndicator.tsx
  administration/src/bp-modules/applications/__mocks__/verificationData.ts
  administration/src/bp-modules/applications/__tests__/ApplicationStatusBar.test.tsx
  administration/src/bp-modules/applications/__tests__/PreVerifiedQuickIndicator.test.tsx
  administration/src/bp-modules/applications/__tests__/VerificationsIndicator.test.tsx
  administration/src/bp-modules/applications/components/VerificationIndicator.tsx
  administration/src/bp-modules/applications/components/VerificationListItem.tsx
  administration/src/bp-modules/applications/constants/index.ts
  administration/src/bp-modules/applications/types.ts
  administration/src/bp-modules/applications/utils/index.ts
  administration/src/bp-modules/components/AccordionExpandButton.tsx
  administration/src/graphql/applications/approveApplicationStatus.graphql
  administration/src/graphql/applications/getApplications.graphql
  administration/src/graphql/applications/withdrawApplication.graphql
  administration/src/mui-modules/application-verification/ApplicationApplicantController.tsx
  administration/src/mui-modules/application-verification/ApplicationApplicantView.tsx
  administration/src/mui-modules/theme.ts
  administration/src/util/translations/de.json
  backend/src/dev/sql/applications.sql
  backend/src/dev/sql/applicationverifications.sql
  backend/src/main/kotlin/app/ehrenamtskarte/backend/application/database/Schema.kt
  backend/src/main/kotlin/app/ehrenamtskarte/backend/application/database/repos/ApplicationRepository.kt
  backend/src/main/kotlin/app/ehrenamtskarte/backend/application/webservice/EakApplicationMutationService.kt
  backend/src/main/kotlin/app/ehrenamtskarte/backend/application/webservice/EakApplicationQueryService.kt
  backend/src/main/kotlin/app/ehrenamtskarte/backend/application/webservice/schema/view/ApplicationView.kt
  backend/src/main/kotlin/app/ehrenamtskarte/backend/cards/webservice/schema/CardMutationService.kt
  backend/src/main/kotlin/app/ehrenamtskarte/backend/migration/migrations/MigrationsRegistry.kt
  backend/src/main/kotlin/app/ehrenamtskarte/backend/migration/migrations/V0028_Add_Application_Status.kt
  docs/working-with-graphql-api.md
  package-lock.json
  specs/backend-api.graphql
Labels: javascript, web, backend

#2285 2284: Update sentry
  backend/build.gradle.kts
  backend/gradle/libs.versions.toml
Labels: not-testable
