Repository digitalfabrik/entitlementcard, pull requests merged in 2025-10, with the labels that each got.

#2530 1707: Added download app page
  administration/src/Router.tsx
  administration/src/mui-modules/download/DownloadPage.tsx
  administration/src/util/translations/de.json
Labels: web

#2531 doc-development-setup
  docs/development-setup.md
  docs/migrations.md
Labels: not-testable, exclude-changelog

#2540 2334: Setup typo
  administration/public/fonts/inter/Inter-Medium.ttf
  administration/public/fonts/inter/Inter-Medium.woff
  administration/public/fonts/inter/Inter-Medium.woff2
  administration/public/fonts/inter/Inter-Regular.ttf
  administration/public/fonts/inter/Inter-Regular.woff
  administration/public/fonts/inter/Inter-Regular.woff2
  administration/public/fonts/inter/Inter-SemiBold.ttf
  administration/public/fonts/inter/Inter-SemiBold.woff
  administration/public/fonts/inter/Inter-SemiBold.woff2
  administration/public/fonts/inter/LICENSE_OFL.txt
  administration/public/fonts/inter/inter.css
  administration/public/index.html
  administration/src/bp-modules/applications/ApplicationCard.tsx
  administration/src/bp-modules/applications/ApplicationPrintView.tsx
  administration/src/bp-modules/applications/ApplicationStatusBarHelpButton.tsx
  administration/src/bp-modules/applications/components/ApplicationStatusNote.tsx
  administration/src/bp-modules/auth/ForgotPasswordController.tsx
  administration/src/bp-modules/auth/Login.tsx
  administration/src/bp-modules/users/RoleHelpButton.tsx
  administration/src/mui-modules/ErrorHandler.tsx
  administration/src/mui-modules/application-verification/ApplicationApplicantView.tsx
  administration/src/mui-modules/application-verification/ApplicationVerifierView.tsx
  administration/src/mui-modules/application/ApplyController.tsx
  administration/src/mui-modules/base/BaseMenu.tsx
  administration/src/mui-modules/imprint/ImprintPage.tsx
  administration/src/mui-modules/theme.ts
  administration/src/project-configs/common/ActivationText.tsx
  administration/src/shared/components/VerificationsView.tsx
  administration/src/types/mui-theme.d.ts
Labels: web

#2524 2335: Unify dialogs
  administration/package.json
  administration/src/KeepAliveToken.tsx
  administration/src/bp-modules/applications/ApplicationCard.tsx
  administration/src/bp-modules/applications/NoteDialogController.tsx
  administration/src/bp-modules/cards/AddCardForm.tsx
  administration/src/bp-modules/cards/ExtensionForms.tsx
  administration/src/bp-modules/components/TextAreaDialog.tsx
  administration/src/bp-modules/components/__tests__/TextAreaDialog.test.tsx
  administration/src/bp-modules/project-settings/ApiTokenSettings.tsx
  administration/src/bp-modules/regions/application-confirmation-note/ApplicationConfirmationNote.tsx
  administration/src/bp-modules/self-service/CardSelfServiceForm.tsx
  administration/src/bp-modules/self-service/CardSelfServiceView.tsx
  administration/src/bp-modules/self-service/components/ActionButton.tsx
  administration/src/bp-modules/stores/StoresButtonBar.tsx
  administration/src/bp-modules/stores/__tests__/StoresButtonBar.test.tsx
  administration/src/bp-modules/users/CreateUserDialog.tsx
  administration/src/bp-modules/users/DeleteUserDialog.tsx
  administration/src/bp-modules/users/EditUserDialog.tsx
  administration/src/bp-modules/users/ManageUsersController.tsx
  administration/src/bp-modules/users/RegionSelector.tsx
  administration/src/bp-modules/users/RoleSelector.tsx
  administration/src/cards/extensions/BirthdayExtension.tsx
  administration/src/cards/extensions/KoblenzReferenceNumberExtension.tsx
  administration/src/cards/extensions/NuernbergPassIdExtension.tsx
  administration/src/cards/extensions/__tests__/BavariaCardTypeExtension.test.tsx
  administration/src/cards/extensions/__tests__/BirthdayExtension.test.tsx
  administration/src/cards/extensions/__tests__/KoblenzReferenceNumberExtension.test.tsx
  administration/src/cards/extensions/__tests__/NuernbergPassIdExtension.test.tsx
  administration/src/cards/extensions/__tests__/StartDayExtension.test.tsx
  administration/src/cards/extensions/components/CardTextField.tsx
  administration/src/cards/extensions/components/__tests__/CardTextField.test.tsx
  administration/src/cards/extensions/extensions.tsx
  administration/src/errors/templates/PasswordResetKeyExpired.tsx
  administration/src/mui-modules/application-verification/ApplicationApplicantView.tsx
  administration/src/mui-modules/application/ApplyController.tsx
  administration/src/mui-modules/application/BasicDialog.tsx
  administration/src/mui-modules/application/ConfirmDialog.tsx
  administration/src/mui-modules/application/DiscardAllInputsButton.tsx
  administration/src/mui-modules/application/forms/StepSendForm.tsx
  administration/src/mui-modules/application/forms/WorkAtOrganizationForm.tsx
  administration/src/mui-modules/base/AlertBox.tsx
  administration/src/util/translations/de.json
  package-lock.json
Labels: web

#2521 release-2025.9.3: update version code
  version.json
Labels: exclude-changelog
